package io.github.ytg1234.fabman.util

import java.nio.file.Path

object Constants {
    const val buildScriptRepositoryMarker = "// FABMAN REPOSITORIES"
    const val buildScriptDependencyMarker = "// FABMAN DEPENDENCIES"

    const val implementationConfiguration = """configurations.getByName("modImplementation")"""

    const val fabmanBuildscriptPath = "fabman.gradle.kts"

    @JvmField
    val fabmanLocalConfigPath: Path = Path.of(".fabman.json")

    @JvmField
    val fabmanGlobalConfigPath: Path = Path.of(System.getProperty("user.home"), ".fabman", "config.json")

    @JvmField
    val fabmanBuildScriptDefaultText = """
        /*
        This file was automatically generated by Fab-Man.
        DO NOT EDIT.
        */
        
        repositories {
            $buildScriptRepositoryMarker
        }
        dependencies {
            $buildScriptDependencyMarker
        }
    """.trimIndent() + "\n"

	// TODO: Make submitting packages actually global and not user-specific
    @JvmField
    val helpGuide =
        """
        |Usage:
        |fabman setup - Run the setup wizard thingy
        |fabman install <package> <repo> - Installs a dependency
        |   Where <package> is:
        |       <group> <artifact> <version>
        |       <package-slug>@<version>
        |fabman uninstall <package> - Uninstalls a package
        |   Where <package> is:
        |       <group> <artifact> <configurations...>
        |       <package-slug>
        |fabman submit <slug> <group> <artifact> <repo> <configurations...> - Adds a dependency to DA LIST
        |fabman help - Shows this
        """.trimMargin("|")
}
