package io.github.ytg1234.fabman.util

import java.nio.file.Path

object Constants {
    const val buildScriptRepositoryMarker = "// FABMAN REPOSITORIES"
    const val buildScriptDependencyMarker = "// FABMAN DEPENDENCIES"

    const val fabmanBuildscriptPath = "fabman.gradle.kts"

    @JvmField
    val fabmanLocalConfigPath: Path = Path.of(".fabman.json")

    @JvmField
    val fabmanGlobalConfigPath: Path = Path.of(System.getProperty("user.home"), ".fabman", "config.json")

    @JvmField
    val fabmanBuildScriptDefaultText = """
        /*
        This file was automatically generated by Fab-Man.
        DO NOT EDIT.
        */
        
        repositories {
            $buildScriptRepositoryMarker
        }
        dependencies {
            $buildScriptDependencyMarker
        }
    """.trimIndent() + "\n"

    val submitPerms = listOf(
        "public_repo"
    )

    const val packageUrlFormat = "https://raw.githubusercontent.com/YTG1234/fabman-repository/main/packages/%s.json"
}
